### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by mplekunov** [COP4331C-Project-Group/PersonalContactManager#15]
- [ ] Search Contacts
- [ ] Create Contact
- [ ] Delete Contact
- [ ] Update Contact

**Comment by mplekunov** [comment]
@COP4331C-Project-Group/front-end

**Comment by nashirj** [comment]
We might implement [lazy loading](https://stackoverflow.com/questions/68436112/scrolling-and-executing-an-event-when-needed-lazy-loading) if we have time
