### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by mplekunov** [COP4331C-Project-Group/PersonalContactManager#5]

**Comment by mplekunov** [comment]
@COP4331C-Project-Group/front-end

**Comment by nashirj** [comment]
Use javascript to determine which view to show the user; simply toggle between the views.

If a user is logged in, we should redirect them to the main page.

**Comment by nashirj** [comment]
Here is a reference for switching between the register and login page: https://webdevtrick.com/html-login-and-signup-form/

**Comment by nashirj** [comment]
This is now done :)
